// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server-template.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerTemplateClient is the client API for ServerTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerTemplateClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerTemplateResponse, error)
}

type serverTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewServerTemplateClient(cc grpc.ClientConnInterface) ServerTemplateClient {
	return &serverTemplateClient{cc}
}

func (c *serverTemplateClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerTemplateResponse, error) {
	out := new(ServerTemplateResponse)
	err := c.cc.Invoke(ctx, "/server_template_proto.ServerTemplate/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerTemplateServer is the server API for ServerTemplate service.
// All implementations must embed UnimplementedServerTemplateServer
// for forward compatibility
type ServerTemplateServer interface {
	Ping(context.Context, *emptypb.Empty) (*ServerTemplateResponse, error)
	mustEmbedUnimplementedServerTemplateServer()
}

// UnimplementedServerTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedServerTemplateServer struct {
}

func (UnimplementedServerTemplateServer) Ping(context.Context, *emptypb.Empty) (*ServerTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedServerTemplateServer) mustEmbedUnimplementedServerTemplateServer() {}

// UnsafeServerTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerTemplateServer will
// result in compilation errors.
type UnsafeServerTemplateServer interface {
	mustEmbedUnimplementedServerTemplateServer()
}

func RegisterServerTemplateServer(s grpc.ServiceRegistrar, srv ServerTemplateServer) {
	s.RegisterService(&ServerTemplate_ServiceDesc, srv)
}

func _ServerTemplate_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerTemplateServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_template_proto.ServerTemplate/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerTemplateServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerTemplate_ServiceDesc is the grpc.ServiceDesc for ServerTemplate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerTemplate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_template_proto.ServerTemplate",
	HandlerType: (*ServerTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ServerTemplate_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server-template.proto",
}
